name: Prepare release

on:
  release:
    types: [published]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  update-package-version-and-push-commit:
    runs-on: ubuntu-22.04
    if: ${{ startsWith(github.event.release.tag_name, 'v') }}
    permissions:
      contents: write
    env:
      TAG_NAME: ${{ github.event.release.tag_name }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: update-package
        run: |
          version_number=$(echo "$TAG_NAME" | sed 's/^v//')
          yq -i -o=json ".version = \"${version_number}\"" package.json

      - name: update-manifest
        run: |
          version_number=$(echo "$TAG_NAME" | sed 's/^v//')
          yq -i -o=json ".version = \"${version_number}\"" manifest.json

      - name: bump-version
        run: |
          version_number=$(echo "$TAG_NAME" | sed 's/^v//')
          sed -i "s/export const VERSION = \".*\";/export const VERSION = \"${version_number}\";/" src/version.ts

      - name: commit
        uses: planetscale/ghcommit-action@25309d8005ac7c3bcd61d3fe19b69e0fe47dbdde # v0.2.20
        with:
          commit_message: "Release version '${{ env.TAG_NAME }}'"
          repo: ${{ github.repository }}
          branch: main
          file_pattern: package.json manifest.json src/version.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
